import re
from datetime import date, timedelta

from click.testing import CliRunner
from sessionkit import AuthService, SqliteAuthStore

from invoice_system.cli.main import cli
from invoice_system.demo_data import DEMO_EMAIL


def _id_from(output: str, pattern: str) -> str:
    match = re.search(pattern, output)
    assert match, f"pattern {pattern!r} not found in output: {output!r}"
    return match.group(1)


def _base_args(db_path) -> list[str]:
    """`--db`/`--attachments-dir` prefix shared by every invocation below -
    both point at a throwaway tmp_path location so a test run never writes
    into the real repo (see attachments.py's docstring on why uploads
    live on disk, not in SQLite)."""
    return ["--db", str(db_path), "--attachments-dir", str(db_path.parent / "attachments")]


def _demo_user_id(auth_db_path) -> str:
    # The demo user's id is a real UUID4 generated by sessionkit (see
    # CLAUDE.md) - nothing predictable like "1" to hardcode in a test
    # anymore, so this looks it up the same way any real caller would:
    # by email, through sessionkit's own API against the auth db the CLI
    # command was pointed at.
    store = SqliteAuthStore.open(str(auth_db_path))
    try:
        user = AuthService(store).find_user(DEMO_EMAIL)
        assert user is not None
        return user.id
    finally:
        store.close()


def test_storage_dir_alone_lays_out_db_and_attachments_subdirectories(tmp_path):
    # No --db/--attachments-dir override here, unlike every other test in
    # this file (see _base_args) - this is the one test that exercises
    # --storage-dir's own derivation logic end to end.
    storage_dir = tmp_path / "my-storage"
    runner = CliRunner()

    # --no-demo never touches the auth db (see init_db's early return) -
    # this just proves the domain db lands under storage_dir/db/.
    result = runner.invoke(cli, ["--storage-dir", str(storage_dir), "init-db", "--no-demo"])
    assert result.exit_code == 0, result.output
    assert (storage_dir / "db" / "invoice_system.db").exists()

    result = runner.invoke(
        cli,
        [
            "--storage-dir",
            str(storage_dir),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    assert result.exit_code == 0, result.output
    account_id = _id_from(result.output, r"Created account (\S+):")

    result = runner.invoke(
        cli,
        [
            "--storage-dir",
            str(storage_dir),
            "expense",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
        ],
    )
    assert result.exit_code == 0, result.output
    expense_id = _id_from(result.output, r"Created expense (\S+) \(")

    receipt_path = tmp_path / "receipt.pdf"
    receipt_path.write_bytes(b"%PDF-1.4 fake receipt")
    result = runner.invoke(
        cli,
        [
            "--storage-dir",
            str(storage_dir),
            "expense",
            "attachment",
            "add",
            expense_id,
            "--file",
            str(receipt_path),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output

    assert (storage_dir / "db" / "invoice_system.db").exists()
    assert (storage_dir / "attachments").is_dir()
    assert list((storage_dir / "attachments").glob("*.pdf")), "expected an uploaded receipt on disk"


def test_storage_dir_init_db_seeds_demo_auth_db_under_it_by_default(tmp_path):
    storage_dir = tmp_path / "my-storage"
    runner = CliRunner()

    result = runner.invoke(cli, ["--storage-dir", str(storage_dir), "init-db"])
    assert result.exit_code == 0, result.output
    assert "demo data" in result.output.lower()
    assert (storage_dir / "db" / "auth.db").exists()
    assert (storage_dir / "db" / "invoice_system.db").exists()


def test_explicit_db_and_attachments_dir_override_storage_dir(tmp_path):
    storage_dir = tmp_path / "unused-storage"
    real_db = tmp_path / "elsewhere.db"
    real_attachments = tmp_path / "elsewhere-attachments"
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "--storage-dir",
            str(storage_dir),
            "--db",
            str(real_db),
            "--attachments-dir",
            str(real_attachments),
            "init-db",
            "--no-demo",
        ],
    )
    assert result.exit_code == 0, result.output
    assert real_db.exists()
    # storage_dir's own db/ subdirectory is never created when both --db
    # and --attachments-dir are given explicitly (see cli()'s guard).
    assert not storage_dir.exists()


def test_full_cli_flow(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    assert result.exit_code == 0, result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    assert result.exit_code == 0, result.output
    account_id = _id_from(result.output, r"Created account (\S+):")
    assert "Acme" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "list",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Acme" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
        ],
    )
    assert result.exit_code == 0, result.output
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    assert result.exit_code == 0, result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "send",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Q-0001" in result.output

    pdf_path = tmp_path / "quote.pdf"
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "pdf",
            quote_id,
            "-o",
            str(pdf_path),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert pdf_path.exists()

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "convert",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "list",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "draft" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "send",
            invoice_id,
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "INV-0001" in result.output

    invoice_pdf_path = tmp_path / "invoice.pdf"
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "pdf",
            invoice_id,
            "-o",
            str(invoice_pdf_path),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert invoice_pdf_path.exists()


def test_account_and_invoice_list_paginate(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    account_ids = []
    for name in ["Acme", "Northwind"]:
        result = runner.invoke(
            cli,
            [
                *_base_args(db_path),
                "account",
                "create",
                "--user-id",
                "1",
                "--business-name",
                name,
                "--email",
                f"{name.lower()}@b.test",
                "--address-line1",
                "1 Main St",
            ],
        )
        account_ids.append(_id_from(result.output, r"Created account (\S+):"))

    result = runner.invoke(
        cli, [*_base_args(db_path), "account", "list", "--user-id", "1", "--page", "1", "--page-size", "1"]
    )
    assert result.exit_code == 0, result.output
    assert "Acme" in result.output
    assert "Northwind" not in result.output
    assert "Page 1 of 2 (total 2)" in result.output

    quote_id = _id_from(
        runner.invoke(
            cli,
            [*_base_args(db_path), "quote", "create", "--user-id", "1", "--account-id", account_ids[0]],
        ).output,
        r"Created quote (\S+) \(draft\)",
    )
    runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(cli, [*_base_args(db_path), "quote", "send", quote_id, "--user-id", "1"])
    runner.invoke(cli, [*_base_args(db_path), "quote", "convert", quote_id, "--user-id", "1"])

    result = runner.invoke(cli, [*_base_args(db_path), "invoice", "list", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "Page 1 of 1 (total 1)" in result.output


def test_invite_create_prints_a_token_and_registration_link(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    result = runner.invoke(cli, [*_base_args(db_path), "invite", "create"])
    assert result.exit_code == 0, result.output
    token = _id_from(result.output, r"Created invite (\S+) \(expires")
    assert f"Registration link: /register?token={token}" in result.output


def test_invite_create_respects_expires_in_days(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    result = runner.invoke(cli, [*_base_args(db_path), "invite", "create", "--expires-in-days", "30"])
    assert result.exit_code == 0, result.output
    assert "Created invite" in result.output


def test_full_expense_cli_flow(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "expense",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
            "--currency",
            "GBP",  # matches the (default) business profile's reporting currency below
        ],
    )
    assert result.exit_code == 0, result.output
    # Unlike "quote create", an expense gets its EXP-0001 number
    # immediately - there's no draft/send lifecycle (see models.Expense).
    assert "EXP-0001" in result.output
    expense_id = _id_from(result.output, r"Created expense (\S+) \(")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "expense",
            "add-item",
            expense_id,
            "--user-id",
            "1",
            "--description",
            "Domain renewal",
            "--quantity",
            "1",
            "--unit-price",
            "12.00",
            "--tax-rate",
            "0.20",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Added line item" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "expense",
            "list",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "EXP-0001" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "expense",
            "monthly-totals",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "14.40" in result.output  # 12.00 net + 20% VAT, this month's row

    pdf_path = tmp_path / "expense.pdf"
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "expense",
            "pdf",
            expense_id,
            "-o",
            str(pdf_path),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert pdf_path.exists()


def test_full_expense_attachment_cli_flow(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")

    result = runner.invoke(
        cli, [*_base_args(db_path), "expense", "create", "--user-id", "1", "--account-id", account_id]
    )
    expense_id = _id_from(result.output, r"Created expense (\S+) \(")

    receipt_path = tmp_path / "receipt.pdf"
    receipt_path.write_bytes(b"%PDF-1.4 fake receipt")

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "attachment",
            "add",
            expense_id,
            "--file",
            str(receipt_path),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "receipt.pdf" in result.output
    attachment_id = _id_from(result.output, r"Uploaded attachment (\S+):")

    result = runner.invoke(
        cli, [*_base_args(db_path), "expense", "attachment", "list", expense_id, "--user-id", "1"]
    )
    assert result.exit_code == 0, result.output
    assert "receipt.pdf" in result.output

    downloaded_path = tmp_path / "downloaded.pdf"
    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "attachment",
            "download",
            expense_id,
            attachment_id,
            "-o",
            str(downloaded_path),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert downloaded_path.read_bytes() == b"%PDF-1.4 fake receipt"

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "attachment",
            "delete",
            expense_id,
            attachment_id,
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output

    result = runner.invoke(
        cli, [*_base_args(db_path), "expense", "attachment", "list", expense_id, "--user-id", "1"]
    )
    assert "receipt.pdf" not in result.output


def test_expense_update_item_and_delete_item(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")

    result = runner.invoke(
        cli, [*_base_args(db_path), "expense", "create", "--user-id", "1", "--account-id", account_id]
    )
    expense_id = _id_from(result.output, r"Created expense (\S+) \(")

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "add-item",
            expense_id,
            "--user-id",
            "1",
            "--description",
            "Domain renewal",
            "--quantity",
            "1",
            "--unit-price",
            "12.00",
        ],
    )
    assert result.exit_code == 0, result.output
    item_id = _id_from(result.output, r"Added line item (\S+)")

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "update-item",
            expense_id,
            item_id,
            "--user-id",
            "1",
            "--description",
            "Domain renewal (2yr)",
            "--quantity",
            "2",
            "--unit-price",
            "12.00",
            "--tax-rate",
            "0.20",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Updated line item" in result.output

    result = runner.invoke(
        cli, [*_base_args(db_path), "expense", "delete-item", expense_id, item_id, "--user-id", "1"]
    )
    assert result.exit_code == 0, result.output
    assert "Deleted line item" in result.output


def test_expense_attachment_add_rejects_a_non_pdf(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli, [*_base_args(db_path), "expense", "create", "--user-id", "1", "--account-id", account_id]
    )
    expense_id = _id_from(result.output, r"Created expense (\S+) \(")

    not_a_pdf = tmp_path / "receipt.txt"
    not_a_pdf.write_text("not a pdf")
    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "attachment",
            "add",
            expense_id,
            "--file",
            str(not_a_pdf),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code != 0


def test_expense_create_requires_existing_account(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "expense",
            "create",
            "--user-id",
            "1",
            "--account-id",
            "does-not-exist",
        ],
    )
    assert result.exit_code != 0


def test_expense_create_with_explicit_date_and_set_date(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    account_id = _id_from(
        runner.invoke(
            cli,
            [
                *_base_args(db_path),
                "account",
                "create",
                "--user-id",
                "1",
                "--business-name",
                "Acme",
                "--email",
                "a@b.test",
                "--address-line1",
                "1 Main St",
            ],
        ).output,
        r"Created account (\S+):",
    )

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
            "--expense-date",
            "2026-02-20",
        ],
    )
    assert result.exit_code == 0, result.output
    expense_id = _id_from(result.output, r"Created expense (\S+) ")

    result = runner.invoke(cli, [*_base_args(db_path), "expense", "list", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "expense date 2026-02-20" in result.output

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "expense",
            "set-date",
            expense_id,
            "--user-id",
            "1",
            "--expense-date",
            "2026-03-01",
        ],
    )
    assert result.exit_code == 0, result.output
    assert f"Updated expense {expense_id}: expense date is now 2026-03-01" in result.output

    result = runner.invoke(cli, [*_base_args(db_path), "expense", "list", "--user-id", "1"])
    assert "expense date 2026-03-01" in result.output


def test_missing_account_returns_nonzero_exit(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "create",
            "--user-id",
            "1",
            "--account-id",
            "does-not-exist",
        ],
    )
    assert result.exit_code != 0


def test_quote_create_and_convert_accept_an_explicit_issue_date(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])
    account_id = _id_from(
        runner.invoke(
            cli,
            [
                *_base_args(db_path),
                "account",
                "create",
                "--user-id",
                "1",
                "--business-name",
                "Acme",
                "--email",
                "a@b.test",
                "--address-line1",
                "1 Main St",
            ],
        ).output,
        r"Created account (\S+):",
    )
    quote_id = _id_from(
        runner.invoke(
            cli,
            [
                *_base_args(db_path),
                "quote",
                "create",
                "--user-id",
                "1",
                "--account-id",
                account_id,
                "--issue-date",
                "2025-12-01",
            ],
        ).output,
        r"Created quote (\S+) \(draft\)",
    )
    runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(cli, [*_base_args(db_path), "quote", "send", quote_id, "--user-id", "1"])
    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "quote",
            "convert",
            quote_id,
            "--user-id",
            "1",
            "--issue-date",
            "2025-11-01",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Converted quote" in result.output


def test_quote_add_item_with_tax_rate(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
        ],
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Design work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
            "--tax-rate",
            "0.20",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Added line item" in result.output


def test_init_db_seeds_demo_data_by_default(tmp_path):
    db_path = tmp_path / "test.db"
    auth_db_path = tmp_path / "auth.db"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["--db", str(db_path), "--attachments-dir", str(db_path.parent / "attachments"), "init-db"],
        env={"INVOICE_SYSTEM_AUTH_DB": str(auth_db_path)},
    )
    assert result.exit_code == 0, result.output
    assert "demo data" in result.output.lower()

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "stats",
            "--user-id",
            _demo_user_id(auth_db_path),
        ],
    )
    assert "Accounts: " in result.output
    assert "Accounts: 0" not in result.output


def test_init_db_no_demo_skips_seeding(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    assert result.exit_code == 0, result.output
    assert result.output.strip() == "Database ready"

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "stats",
            "--user-id",
            "1",
        ],
    )
    assert "Accounts: 0" in result.output


def test_init_db_demo_is_idempotent(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    env = {"INVOICE_SYSTEM_AUTH_DB": str(tmp_path / "auth.db")}
    runner.invoke(
        cli,
        ["--db", str(db_path), "--attachments-dir", str(db_path.parent / "attachments"), "init-db"],
        env=env,
    )
    result = runner.invoke(
        cli,
        ["--db", str(db_path), "--attachments-dir", str(db_path.parent / "attachments"), "init-db"],
        env=env,
    )

    assert result.exit_code == 0, result.output
    assert "already present" in result.output.lower()


def test_stats(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "stats",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Accounts: 1" in result.output


def test_stats_is_isolated_per_user(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "stats",
            "--user-id",
            "2",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Accounts: 0" in result.output


def test_account_update(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "update",
            account_id,
            "--user-id",
            "1",
            "--business-name",
            "Acme Ltd",
            "--email",
            "b@b.test",
            "--address-line1",
            "2 High St",
        ],
    )
    assert result.exit_code == 0, result.output
    assert f"Updated account {account_id}: Acme Ltd" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "list",
            "--user-id",
            "1",
        ],
    )
    assert "Acme Ltd" in result.output


def test_account_update_missing_account_returns_nonzero_exit(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "update",
            "does-not-exist",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    assert result.exit_code != 0


def test_domain_create_list_update_delete(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    account_id = _id_from(
        runner.invoke(
            cli,
            [
                *_base_args(db_path),
                "account",
                "create",
                "--user-id",
                "1",
                "--business-name",
                "Acme",
                "--email",
                "a@b.test",
                "--address-line1",
                "1 Main St",
            ],
        ).output,
        r"Created account (\S+):",
    )

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "domain",
            "create",
            account_id,
            "--user-id",
            "1",
            "--domain-name",
            "acme.test",
            "--expiry-date",
            "2027-01-01",
            "--registrar",
            "123-Reg",
            "--auto-renew",
        ],
    )
    assert result.exit_code == 0, result.output
    domain_id = _id_from(result.output, r"Created domain (\S+):")

    result = runner.invoke(cli, [*_base_args(db_path), "domain", "list", account_id, "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "acme.test" in result.output
    assert "auto-renew" in result.output

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "domain",
            "update",
            account_id,
            domain_id,
            "--user-id",
            "1",
            "--domain-name",
            "acme.co.uk",
            "--expiry-date",
            "2028-01-01",
            "--registrar",
            "GoDaddy",
            "--no-auto-renew",
        ],
    )
    assert result.exit_code == 0, result.output
    assert f"Updated domain {domain_id}: acme.co.uk" in result.output

    result = runner.invoke(cli, [*_base_args(db_path), "domain", "list", account_id, "--user-id", "1"])
    assert "acme.co.uk" in result.output
    assert "manual renewal" in result.output

    result = runner.invoke(
        cli, [*_base_args(db_path), "domain", "delete", account_id, domain_id, "--user-id", "1"]
    )
    assert result.exit_code == 0, result.output
    assert f"Deleted domain {domain_id}" in result.output

    result = runner.invoke(cli, [*_base_args(db_path), "domain", "list", account_id, "--user-id", "1"])
    assert result.output.strip() == ""


def test_domain_create_requires_existing_account(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "domain",
            "create",
            "does-not-exist",
            "--user-id",
            "1",
            "--domain-name",
            "acme.test",
            "--expiry-date",
            "2027-01-01",
            "--registrar",
            "123-Reg",
        ],
    )
    assert result.exit_code != 0


def test_registrar_create_list_update_delete(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, [*_base_args(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "registrar",
            "create",
            "--user-id",
            "1",
            "--name",
            "123-Reg",
            "--notes",
            "https://123-reg.co.uk",
        ],
    )
    assert result.exit_code == 0, result.output
    registrar_id = _id_from(result.output, r"Created registrar (\S+):")

    runner.invoke(cli, [*_base_args(db_path), "registrar", "create", "--user-id", "1", "--name", "GoDaddy"])

    result = runner.invoke(cli, [*_base_args(db_path), "registrar", "list", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    # Alphabetical, not creation order (see models.Registrar).
    assert result.output.index("123-Reg") < result.output.index("GoDaddy")

    result = runner.invoke(
        cli,
        [
            *_base_args(db_path),
            "registrar",
            "update",
            registrar_id,
            "--user-id",
            "1",
            "--name",
            "123 Reg Ltd",
        ],
    )
    assert result.exit_code == 0, result.output
    assert f"Updated registrar {registrar_id}: 123 Reg Ltd" in result.output

    result = runner.invoke(cli, [*_base_args(db_path), "registrar", "delete", registrar_id, "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert f"Deleted registrar {registrar_id}" in result.output

    result = runner.invoke(cli, [*_base_args(db_path), "registrar", "list", "--user-id", "1"])
    assert "123 Reg Ltd" not in result.output
    assert "GoDaddy" in result.output


def test_settings_show_defaults_then_set_and_show_again(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "settings",
            "show",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Payment terms (days): 30" in result.output
    assert "Quote validity (days): 30" in result.output
    assert "Currency: GBP" in result.output
    assert "Business name: -" in result.output
    assert "Bank account name: -" in result.output
    assert "Quote header: -" in result.output
    assert "Invoice header: -" in result.output
    assert "Expense header: -" in result.output
    assert "Accent colour: -" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--payment-terms-days",
            "5",
            "--currency",
            "usd",
            "--bank-account-name",
            "Acme Consulting Ltd",
            "--bank-sort-code",
            "12-34-56",
            "--bank-account-number",
            "12345678",
            "--quote-header",
            "Acme Consulting",
            "--quote-footer",
            "Valid for 30 days.",
            "--invoice-header",
            "Acme Consulting",
            "--invoice-footer",
            "Thank you!",
            "--expense-header",
            "Acme Consulting",
            "--expense-footer",
            "Internal use only.",
            "--accent-color",
            "#2563EB",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Saved business profile for user 1" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "settings",
            "show",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Name: Ada Lovelace" in result.output
    assert "Business name: Acme Consulting" in result.output
    assert "Address line 1: -" in result.output
    assert "Payment terms (days): 5" in result.output
    assert "Currency: USD" in result.output
    assert "Bank account name: Acme Consulting Ltd" in result.output
    assert "Bank sort code: 12-34-56" in result.output
    assert "Bank account number: 12345678" in result.output
    assert "Quote header: Acme Consulting" in result.output
    assert "Quote footer: Valid for 30 days." in result.output
    assert "Invoice header: Acme Consulting" in result.output
    assert "Invoice footer: Thank you!" in result.output
    assert "Expense header: Acme Consulting" in result.output
    assert "Expense footer: Internal use only." in result.output
    assert "Accent colour: #2563EB" in result.output


def test_settings_set_requires_first_name(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme",
        ],
    )
    assert result.exit_code != 0


def test_invoice_send_with_user_id_uses_the_profiles_payment_terms(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--payment-terms-days",
            "5",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
        ],
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "send",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "convert",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "send",
            invoice_id,
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    expected_due = date.today() + timedelta(days=5)
    assert f"due {expected_due.isoformat()}" in result.output


def test_invoice_pay(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
        ],
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "send",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "convert",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "send",
            invoice_id,
            "--user-id",
            "1",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "pay",
            invoice_id,
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert f"Invoice {invoice_id} marked paid" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "list",
            "--user-id",
            "1",
        ],
    )
    assert "paid" in result.output


def test_invoice_pay_a_draft_invoice_returns_nonzero_exit(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
        ],
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "send",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "convert",
            quote_id,
            "--user-id",
            "1",
        ],
    )
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "pay",
            invoice_id,
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code != 0


def test_invoice_monthly_totals(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--currency",
            "GBP",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "invoice",
            "monthly-totals",
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert result.output.count("\n") == 12
    assert "GBP" in result.output


def test_quote_and_invoice_pdf_accept_a_user_id(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--address-line1",
            "1 Market St",
            "--town-or-city",
            "London",
            "--postcode",
            "SW1A 1AA",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "create",
            "--user-id",
            "1",
            "--account-id",
            account_id,
        ],
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")

    pdf_path = tmp_path / "quote.pdf"
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "quote",
            "pdf",
            quote_id,
            "-o",
            str(pdf_path),
            "--user-id",
            "1",
        ],
    )
    assert result.exit_code == 0, result.output
    assert pdf_path.exists()


def test_accounts_are_isolated_per_user(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "init-db",
            "--no-demo",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "User 1's Client",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "create",
            "--user-id",
            "2",
            "--business-name",
            "User 2's Client",
            "--email",
            "b@b.test",
            "--address-line1",
            "2 High St",
        ],
    )

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "list",
            "--user-id",
            "1",
        ],
    )
    assert "User 1's Client" in result.output
    assert "User 2's Client" not in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "--attachments-dir",
            str(db_path.parent / "attachments"),
            "account",
            "list",
            "--user-id",
            "2",
        ],
    )
    assert "User 2's Client" in result.output
    assert "User 1's Client" not in result.output
