import re
from datetime import date, timedelta

from click.testing import CliRunner
from sessionkit import AuthService, SqliteAuthStore

from invoice_system.cli.main import cli
from invoice_system.demo_data import DEMO_EMAIL


def _id_from(output: str, pattern: str) -> str:
    match = re.search(pattern, output)
    assert match, f"pattern {pattern!r} not found in output: {output!r}"
    return match.group(1)


def _demo_user_id(auth_db_path) -> str:
    # The demo user's id is a real UUID4 generated by sessionkit (see
    # CLAUDE.md) - nothing predictable like "1" to hardcode in a test
    # anymore, so this looks it up the same way any real caller would:
    # by email, through sessionkit's own API against the auth db the CLI
    # command was pointed at.
    store = SqliteAuthStore.open(str(auth_db_path))
    try:
        user = AuthService(store).find_user(DEMO_EMAIL)
        assert user is not None
        return user.id
    finally:
        store.close()


def test_full_cli_flow(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()

    result = runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    assert result.exit_code == 0, result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    assert result.exit_code == 0, result.output
    account_id = _id_from(result.output, r"Created account (\S+):")
    assert "Acme" in result.output

    result = runner.invoke(cli, ["--db", str(db_path), "account", "list", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "Acme" in result.output

    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "create", "--user-id", "1", "--account-id", account_id]
    )
    assert result.exit_code == 0, result.output
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    assert result.exit_code == 0, result.output

    result = runner.invoke(cli, ["--db", str(db_path), "quote", "send", quote_id, "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "Q-0001" in result.output

    pdf_path = tmp_path / "quote.pdf"
    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "pdf", quote_id, "-o", str(pdf_path), "--user-id", "1"]
    )
    assert result.exit_code == 0, result.output
    assert pdf_path.exists()

    result = runner.invoke(cli, ["--db", str(db_path), "quote", "convert", quote_id, "--user-id", "1"])
    assert result.exit_code == 0, result.output
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")

    result = runner.invoke(cli, ["--db", str(db_path), "invoice", "list", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "draft" in result.output

    result = runner.invoke(cli, ["--db", str(db_path), "invoice", "send", invoice_id, "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "INV-0001" in result.output

    invoice_pdf_path = tmp_path / "invoice.pdf"
    result = runner.invoke(
        cli,
        ["--db", str(db_path), "invoice", "pdf", invoice_id, "-o", str(invoice_pdf_path), "--user-id", "1"],
    )
    assert result.exit_code == 0, result.output
    assert invoice_pdf_path.exists()


def test_full_expense_cli_flow(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")

    result = runner.invoke(
        cli, ["--db", str(db_path), "expense", "create", "--user-id", "1", "--account-id", account_id]
    )
    assert result.exit_code == 0, result.output
    # Unlike "quote create", an expense gets its EXP-0001 number
    # immediately - there's no draft/send lifecycle (see models.Expense).
    assert "EXP-0001" in result.output
    expense_id = _id_from(result.output, r"Created expense (\S+) \(")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "expense",
            "add-item",
            expense_id,
            "--user-id",
            "1",
            "--description",
            "Domain renewal",
            "--quantity",
            "1",
            "--unit-price",
            "12.00",
            "--tax-rate",
            "0.20",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Added line item" in result.output

    result = runner.invoke(cli, ["--db", str(db_path), "expense", "list", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "EXP-0001" in result.output

    pdf_path = tmp_path / "expense.pdf"
    result = runner.invoke(
        cli, ["--db", str(db_path), "expense", "pdf", expense_id, "-o", str(pdf_path), "--user-id", "1"]
    )
    assert result.exit_code == 0, result.output
    assert pdf_path.exists()


def test_expense_create_requires_existing_account(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        ["--db", str(db_path), "expense", "create", "--user-id", "1", "--account-id", "does-not-exist"],
    )
    assert result.exit_code != 0


def test_missing_account_returns_nonzero_exit(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        ["--db", str(db_path), "quote", "create", "--user-id", "1", "--account-id", "does-not-exist"],
    )
    assert result.exit_code != 0


def test_quote_add_item_with_tax_rate(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "create", "--user-id", "1", "--account-id", account_id]
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Design work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
            "--tax-rate",
            "0.20",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Added line item" in result.output


def test_init_db_seeds_demo_data_by_default(tmp_path):
    db_path = tmp_path / "test.db"
    auth_db_path = tmp_path / "auth.db"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["--db", str(db_path), "init-db"],
        env={"INVOICE_SYSTEM_AUTH_DB": str(auth_db_path)},
    )
    assert result.exit_code == 0, result.output
    assert "demo data" in result.output.lower()

    result = runner.invoke(cli, ["--db", str(db_path), "stats", "--user-id", _demo_user_id(auth_db_path)])
    assert "Accounts: " in result.output
    assert "Accounts: 0" not in result.output


def test_init_db_no_demo_skips_seeding(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    result = runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    assert result.exit_code == 0, result.output
    assert result.output.strip() == "Database ready"

    result = runner.invoke(cli, ["--db", str(db_path), "stats", "--user-id", "1"])
    assert "Accounts: 0" in result.output


def test_init_db_demo_is_idempotent(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    env = {"INVOICE_SYSTEM_AUTH_DB": str(tmp_path / "auth.db")}
    runner.invoke(cli, ["--db", str(db_path), "init-db"], env=env)
    result = runner.invoke(cli, ["--db", str(db_path), "init-db"], env=env)

    assert result.exit_code == 0, result.output
    assert "already present" in result.output.lower()


def test_stats(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )

    result = runner.invoke(cli, ["--db", str(db_path), "stats", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "Accounts: 1" in result.output


def test_stats_is_isolated_per_user(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )

    result = runner.invoke(cli, ["--db", str(db_path), "stats", "--user-id", "2"])
    assert result.exit_code == 0, result.output
    assert "Accounts: 0" in result.output


def test_account_update(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "update",
            account_id,
            "--user-id",
            "1",
            "--business-name",
            "Acme Ltd",
            "--email",
            "b@b.test",
            "--address-line1",
            "2 High St",
        ],
    )
    assert result.exit_code == 0, result.output
    assert f"Updated account {account_id}: Acme Ltd" in result.output

    result = runner.invoke(cli, ["--db", str(db_path), "account", "list", "--user-id", "1"])
    assert "Acme Ltd" in result.output


def test_account_update_missing_account_returns_nonzero_exit(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "update",
            "does-not-exist",
            "--user-id",
            "1",
            "--business-name",
            "Acme",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    assert result.exit_code != 0


def test_settings_show_defaults_then_set_and_show_again(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])

    result = runner.invoke(cli, ["--db", str(db_path), "settings", "show", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "Payment terms (days): 30" in result.output
    assert "Currency: GBP" in result.output
    assert "Business name: -" in result.output
    assert "Bank account name: -" in result.output
    assert "Document header: -" in result.output

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--payment-terms-days",
            "5",
            "--currency",
            "usd",
            "--bank-account-name",
            "Acme Consulting Ltd",
            "--bank-sort-code",
            "12-34-56",
            "--bank-account-number",
            "12345678",
            "--document-header",
            "Acme Consulting",
            "--document-footer",
            "Thank you!",
        ],
    )
    assert result.exit_code == 0, result.output
    assert "Saved business profile for user 1" in result.output

    result = runner.invoke(cli, ["--db", str(db_path), "settings", "show", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert "Name: Ada Lovelace" in result.output
    assert "Business name: Acme Consulting" in result.output
    assert "Address line 1: -" in result.output
    assert "Payment terms (days): 5" in result.output
    assert "Currency: USD" in result.output
    assert "Bank account name: Acme Consulting Ltd" in result.output
    assert "Bank sort code: 12-34-56" in result.output
    assert "Bank account number: 12345678" in result.output
    assert "Document header: Acme Consulting" in result.output
    assert "Document footer: Thank you!" in result.output


def test_settings_set_requires_first_name(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])

    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme",
        ],
    )
    assert result.exit_code != 0


def test_invoice_send_with_user_id_uses_the_profiles_payment_terms(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--payment-terms-days",
            "5",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "create", "--user-id", "1", "--account-id", account_id]
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(cli, ["--db", str(db_path), "quote", "send", quote_id, "--user-id", "1"])
    result = runner.invoke(cli, ["--db", str(db_path), "quote", "convert", quote_id, "--user-id", "1"])
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")

    result = runner.invoke(cli, ["--db", str(db_path), "invoice", "send", invoice_id, "--user-id", "1"])
    assert result.exit_code == 0, result.output
    expected_due = date.today() + timedelta(days=5)
    assert f"due {expected_due.isoformat()}" in result.output


def test_invoice_pay(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "create", "--user-id", "1", "--account-id", account_id]
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(cli, ["--db", str(db_path), "quote", "send", quote_id, "--user-id", "1"])
    result = runner.invoke(cli, ["--db", str(db_path), "quote", "convert", quote_id, "--user-id", "1"])
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")
    runner.invoke(cli, ["--db", str(db_path), "invoice", "send", invoice_id, "--user-id", "1"])

    result = runner.invoke(cli, ["--db", str(db_path), "invoice", "pay", invoice_id, "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert f"Invoice {invoice_id} marked paid" in result.output

    result = runner.invoke(cli, ["--db", str(db_path), "invoice", "list", "--user-id", "1"])
    assert "paid" in result.output


def test_invoice_pay_a_draft_invoice_returns_nonzero_exit(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "create", "--user-id", "1", "--account-id", account_id]
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "quote",
            "add-item",
            quote_id,
            "--user-id",
            "1",
            "--description",
            "Work",
            "--quantity",
            "1",
            "--unit-price",
            "100.00",
        ],
    )
    runner.invoke(cli, ["--db", str(db_path), "quote", "send", quote_id, "--user-id", "1"])
    result = runner.invoke(cli, ["--db", str(db_path), "quote", "convert", quote_id, "--user-id", "1"])
    invoice_id = _id_from(result.output, r"to invoice (\S+)$")

    result = runner.invoke(cli, ["--db", str(db_path), "invoice", "pay", invoice_id, "--user-id", "1"])
    assert result.exit_code != 0


def test_invoice_monthly_totals(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--currency",
            "GBP",
        ],
    )

    result = runner.invoke(cli, ["--db", str(db_path), "invoice", "monthly-totals", "--user-id", "1"])
    assert result.exit_code == 0, result.output
    assert result.output.count("\n") == 12
    assert "GBP" in result.output


def test_quote_and_invoice_pdf_accept_a_user_id(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "settings",
            "set",
            "--user-id",
            "1",
            "--first-name",
            "Ada",
            "--last-name",
            "Lovelace",
            "--business-name",
            "Acme Consulting",
            "--address-line1",
            "1 Market St",
            "--town-or-city",
            "London",
            "--postcode",
            "SW1A 1AA",
        ],
    )
    result = runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "Client Co",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    account_id = _id_from(result.output, r"Created account (\S+):")
    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "create", "--user-id", "1", "--account-id", account_id]
    )
    quote_id = _id_from(result.output, r"Created quote (\S+) \(draft\)")

    pdf_path = tmp_path / "quote.pdf"
    result = runner.invoke(
        cli, ["--db", str(db_path), "quote", "pdf", quote_id, "-o", str(pdf_path), "--user-id", "1"]
    )
    assert result.exit_code == 0, result.output
    assert pdf_path.exists()


def test_accounts_are_isolated_per_user(tmp_path):
    db_path = tmp_path / "test.db"
    runner = CliRunner()
    runner.invoke(cli, ["--db", str(db_path), "init-db", "--no-demo"])
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "1",
            "--business-name",
            "User 1's Client",
            "--email",
            "a@b.test",
            "--address-line1",
            "1 Main St",
        ],
    )
    runner.invoke(
        cli,
        [
            "--db",
            str(db_path),
            "account",
            "create",
            "--user-id",
            "2",
            "--business-name",
            "User 2's Client",
            "--email",
            "b@b.test",
            "--address-line1",
            "2 High St",
        ],
    )

    result = runner.invoke(cli, ["--db", str(db_path), "account", "list", "--user-id", "1"])
    assert "User 1's Client" in result.output
    assert "User 2's Client" not in result.output

    result = runner.invoke(cli, ["--db", str(db_path), "account", "list", "--user-id", "2"])
    assert "User 2's Client" in result.output
    assert "User 1's Client" not in result.output
