import sqlite3
import threading
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

from ..models import (
    Account,
    BusinessProfile,
    Expense,
    ExpenseAttachment,
    Invoice,
    InvoiceStatus,
    LineItem,
    Organisation,
    Quote,
    QuoteStatus,
    RegistrationInvite,
)
from .schema import MIGRATIONS


class SqliteRepository:
    def __init__(self, db_path: str | Path) -> None:
        self._conn = sqlite3.connect(str(db_path), check_same_thread=False)
        self._conn.row_factory = sqlite3.Row
        self._lock = threading.Lock()

    def close(self) -> None:
        self._conn.close()

    def migrate(self) -> None:
        with self._lock:
            current = self._conn.execute("PRAGMA user_version").fetchone()[0]
            for version, script in enumerate(MIGRATIONS, start=1):
                if version <= current:
                    continue
                self._conn.executescript(script)
                self._conn.execute(f"PRAGMA user_version = {version}")
            self._conn.commit()

    # -- Organisations ---------------------------------------------------------

    def get_organisation_id_for_user(self, user_id: str) -> str | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT organisation_id FROM organisation_members WHERE user_id = ?", (user_id,)
            ).fetchone()
        return row["organisation_id"] if row else None

    def create_organisation(self, organisation: Organisation) -> Organisation:
        # organisation.id is already a UUID4 (see ids.py) generated by the
        # service layer before this is called - persistence only inserts
        # what it's given, never generates an id itself (see CLAUDE.md
        # architecture rules).
        with self._lock:
            self._conn.execute(
                "INSERT INTO organisations (id, name, created_at) VALUES (?, ?, ?)",
                (organisation.id, organisation.name, organisation.created_at.isoformat()),
            )
            self._conn.commit()
            return organisation

    def add_organisation_member(self, organisation_id: str, user_id: str) -> str:
        # Check-then-insert, but atomic under the single shared-connection
        # lock (see CLAUDE.md) rather than two separate locked calls - two
        # concurrent first-ever requests for the same brand-new user would
        # otherwise both pass OrganisationService's initial "does this user
        # have an organisation" check, then race here: without this being
        # one atomic operation, the loser's plain INSERT would violate
        # organisation_members.user_id's UNIQUE constraint and crash the
        # request instead of just returning the winner's organisation_id
        # (the Organisation row it built is left an orphan, matching this
        # method's docstring on models.Organisation - harmless, since
        # nothing ever looks up an Organisation except via its members).
        with self._lock:
            row = self._conn.execute(
                "SELECT organisation_id FROM organisation_members WHERE user_id = ?", (user_id,)
            ).fetchone()
            if row is not None:
                return row["organisation_id"]
            self._conn.execute(
                "INSERT INTO organisation_members (organisation_id, user_id, created_at) VALUES (?, ?, ?)",
                (organisation_id, user_id, datetime.now().astimezone().isoformat()),
            )
            self._conn.commit()
            return organisation_id

    # -- Accounts ----------------------------------------------------------

    def create_account(self, account: Account) -> Account:
        with self._lock:
            self._conn.execute(
                "INSERT INTO accounts (id, organisation_id, business_name, contact_name, email, phone, "
                "address_line1, address_line2, town_or_city, county, postcode, created_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    account.id,
                    account.organisation_id,
                    account.business_name,
                    account.contact_name,
                    account.email,
                    account.phone,
                    account.address_line1,
                    account.address_line2,
                    account.town_or_city,
                    account.county,
                    account.postcode,
                    account.created_at.isoformat(),
                ),
            )
            self._conn.commit()
            return account

    def get_account(self, organisation_id: str, account_id: str) -> Account | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM accounts WHERE id = ? AND organisation_id = ?", (account_id, organisation_id)
            ).fetchone()
        return self._row_to_account(row) if row else None

    def list_accounts(
        self, organisation_id: str, *, query: str | None = None, limit: int | None = None, offset: int = 0
    ) -> tuple[list[Account], int]:
        # ORDER BY rowid, not id or created_at - id is a random UUID4 (see
        # ids.py) with no ordering relationship to insertion order, and two
        # rows can share the same created_at (a frozen/fake clock in tests,
        # or plain clock resolution in production). Every SQLite table not
        # declared WITHOUT ROWID keeps an implicit, monotonically-increasing
        # rowid regardless of its declared PRIMARY KEY type - it's never
        # selected or exposed to any caller (not part of any dataclass or
        # API response), so ordering by it doesn't reintroduce the
        # information leak switching to UUIDs was meant to close. It's also
        # exactly what makes `limit`/`offset` below well-defined - a stable
        # order, not liable to reshuffle between two calls a page apart.
        #
        # `limit=None` (used internally by StatsService/monthly_totals,
        # which need every row, not one page) skips LIMIT/OFFSET entirely
        # and returns `len(rows)` as the total rather than issuing a second
        # COUNT query for a number it already has.
        where = "organisation_id = ?"
        params: list[object] = [organisation_id]
        if query:
            pattern = f"%{query}%"
            where += (
                " AND (business_name LIKE ? OR contact_name LIKE ? OR email LIKE ? OR phone LIKE ? OR "
                "address_line1 LIKE ? OR address_line2 LIKE ? OR town_or_city LIKE ? OR county LIKE ? OR "
                "postcode LIKE ?)"
            )
            params.extend([pattern] * 9)

        with self._lock:
            if limit is None:
                rows = self._conn.execute(
                    f"SELECT * FROM accounts WHERE {where} ORDER BY rowid", params
                ).fetchall()
                total = len(rows)
            else:
                total = self._conn.execute(f"SELECT COUNT(*) FROM accounts WHERE {where}", params).fetchone()[
                    0
                ]
                rows = self._conn.execute(
                    f"SELECT * FROM accounts WHERE {where} ORDER BY rowid LIMIT ? OFFSET ?",
                    [*params, limit, offset],
                ).fetchall()
        return [self._row_to_account(row) for row in rows], total

    def update_account(self, account: Account) -> Account:
        with self._lock:
            self._conn.execute(
                "UPDATE accounts SET business_name = ?, contact_name = ?, email = ?, phone = ?, "
                "address_line1 = ?, address_line2 = ?, town_or_city = ?, county = ?, postcode = ? "
                "WHERE id = ? AND organisation_id = ?",
                (
                    account.business_name,
                    account.contact_name,
                    account.email,
                    account.phone,
                    account.address_line1,
                    account.address_line2,
                    account.town_or_city,
                    account.county,
                    account.postcode,
                    account.id,
                    account.organisation_id,
                ),
            )
            self._conn.commit()
            return account

    @staticmethod
    def _row_to_account(row: sqlite3.Row) -> Account:
        return Account(
            id=row["id"],
            organisation_id=row["organisation_id"],
            business_name=row["business_name"],
            contact_name=row["contact_name"],
            email=row["email"],
            phone=row["phone"],
            address_line1=row["address_line1"],
            address_line2=row["address_line2"],
            town_or_city=row["town_or_city"],
            county=row["county"],
            postcode=row["postcode"],
            created_at=datetime.fromisoformat(row["created_at"]),
        )

    # -- Business profiles -----------------------------------------------------

    def get_business_profile(self, user_id: str) -> BusinessProfile | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM business_profiles WHERE user_id = ?", (user_id,)
            ).fetchone()
        return self._row_to_business_profile(row) if row else None

    def upsert_business_profile(self, profile: BusinessProfile) -> BusinessProfile:
        with self._lock:
            self._conn.execute(
                "INSERT INTO business_profiles (id, user_id, title, first_name, last_name, "
                "business_name, address_line1, address_line2, town_or_city, county, postcode, "
                "payment_terms_days, currency, utr, vat_number, bank_account_name, bank_sort_code, "
                "bank_account_number, document_header, document_footer, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) "
                "ON CONFLICT(user_id) DO UPDATE SET "
                "title = excluded.title, "
                "first_name = excluded.first_name, "
                "last_name = excluded.last_name, "
                "business_name = excluded.business_name, "
                "address_line1 = excluded.address_line1, "
                "address_line2 = excluded.address_line2, "
                "town_or_city = excluded.town_or_city, "
                "county = excluded.county, "
                "postcode = excluded.postcode, "
                "payment_terms_days = excluded.payment_terms_days, "
                "currency = excluded.currency, "
                "utr = excluded.utr, "
                "vat_number = excluded.vat_number, "
                "bank_account_name = excluded.bank_account_name, "
                "bank_sort_code = excluded.bank_sort_code, "
                "bank_account_number = excluded.bank_account_number, "
                "document_header = excluded.document_header, "
                "document_footer = excluded.document_footer, "
                "updated_at = excluded.updated_at",
                (
                    profile.id,
                    profile.user_id,
                    profile.title,
                    profile.first_name,
                    profile.last_name,
                    profile.business_name,
                    profile.address_line1,
                    profile.address_line2,
                    profile.town_or_city,
                    profile.county,
                    profile.postcode,
                    profile.payment_terms_days,
                    profile.currency,
                    profile.utr,
                    profile.vat_number,
                    profile.bank_account_name,
                    profile.bank_sort_code,
                    profile.bank_account_number,
                    profile.document_header,
                    profile.document_footer,
                    profile.created_at.isoformat(),
                    profile.updated_at.isoformat(),
                ),
            )
            self._conn.commit()
            row = self._conn.execute(
                "SELECT * FROM business_profiles WHERE user_id = ?", (profile.user_id,)
            ).fetchone()
        return self._row_to_business_profile(row)

    @staticmethod
    def _row_to_business_profile(row: sqlite3.Row) -> BusinessProfile:
        return BusinessProfile(
            id=row["id"],
            user_id=row["user_id"],
            title=row["title"],
            first_name=row["first_name"],
            last_name=row["last_name"],
            business_name=row["business_name"],
            address_line1=row["address_line1"],
            address_line2=row["address_line2"],
            town_or_city=row["town_or_city"],
            county=row["county"],
            postcode=row["postcode"],
            payment_terms_days=row["payment_terms_days"],
            currency=row["currency"],
            utr=row["utr"],
            vat_number=row["vat_number"],
            bank_account_name=row["bank_account_name"],
            bank_sort_code=row["bank_sort_code"],
            bank_account_number=row["bank_account_number"],
            document_header=row["document_header"],
            document_footer=row["document_footer"],
            created_at=datetime.fromisoformat(row["created_at"]),
            updated_at=datetime.fromisoformat(row["updated_at"]),
        )

    # -- Quotes --------------------------------------------------------------

    def create_quote(self, quote: Quote) -> Quote:
        with self._lock:
            self._conn.execute(
                "INSERT INTO quotes (id, organisation_id, account_id, number, status, currency, "
                "issue_date, expiry_date, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    quote.id,
                    quote.organisation_id,
                    quote.account_id,
                    quote.number,
                    quote.status.value,
                    quote.currency,
                    quote.issue_date.isoformat(),
                    quote.expiry_date.isoformat() if quote.expiry_date else None,
                    quote.created_at.isoformat(),
                ),
            )
            self._conn.commit()
            return quote

    def get_quote(self, organisation_id: str, quote_id: str) -> Quote | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM quotes WHERE id = ? AND organisation_id = ?", (quote_id, organisation_id)
            ).fetchone()
            if row is None:
                return None
            item_rows = self._conn.execute(
                "SELECT * FROM quote_line_items WHERE quote_id = ? ORDER BY position", (quote_id,)
            ).fetchall()
        return self._row_to_quote(row, item_rows)

    def list_quotes(
        self,
        organisation_id: str,
        *,
        account_id: str | None = None,
        account_name: str | None = None,
        status: QuoteStatus | None = None,
        limit: int | None = None,
        offset: int = 0,
    ) -> tuple[list[Quote], int]:
        # ORDER BY quotes.rowid, limit=None meaning "every row" - see
        # list_accounts' comment above for both.
        join = ""
        where = "quotes.organisation_id = ?"
        params: list[object] = [organisation_id]
        if account_id is not None:
            where += " AND quotes.account_id = ?"
            params.append(account_id)
        if status is not None:
            where += " AND quotes.status = ?"
            params.append(status.value)
        if account_name:
            # A quote's account_id always points at exactly one account, so
            # this join can never multiply a quote's row - no DISTINCT needed.
            join = " JOIN accounts ON accounts.id = quotes.account_id"
            where += " AND accounts.business_name LIKE ?"
            params.append(f"%{account_name}%")

        with self._lock:
            if limit is None:
                rows = self._conn.execute(
                    f"SELECT quotes.* FROM quotes{join} WHERE {where} ORDER BY quotes.rowid", params
                ).fetchall()
                total = len(rows)
            else:
                total = self._conn.execute(
                    f"SELECT COUNT(*) FROM quotes{join} WHERE {where}", params
                ).fetchone()[0]
                rows = self._conn.execute(
                    f"SELECT quotes.* FROM quotes{join} WHERE {where} ORDER BY quotes.rowid LIMIT ? OFFSET ?",
                    [*params, limit, offset],
                ).fetchall()
            quotes = []
            for row in rows:
                item_rows = self._conn.execute(
                    "SELECT * FROM quote_line_items WHERE quote_id = ? ORDER BY position", (row["id"],)
                ).fetchall()
                quotes.append(self._row_to_quote(row, item_rows))
        return quotes, total

    def update_quote(self, quote: Quote) -> Quote:
        with self._lock:
            self._conn.execute(
                "UPDATE quotes SET number = ?, status = ?, currency = ?, issue_date = ?, expiry_date = ? "
                "WHERE id = ? AND organisation_id = ?",
                (
                    quote.number,
                    quote.status.value,
                    quote.currency,
                    quote.issue_date.isoformat(),
                    quote.expiry_date.isoformat() if quote.expiry_date else None,
                    quote.id,
                    quote.organisation_id,
                ),
            )
            self._conn.commit()
            return quote

    def add_quote_line_item(self, quote_id: str, item: LineItem) -> LineItem:
        with self._lock:
            self._conn.execute(
                "INSERT INTO quote_line_items "
                "(id, quote_id, description, quantity, unit_price, tax_rate, position) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    item.id,
                    quote_id,
                    item.description,
                    str(item.quantity),
                    str(item.unit_price),
                    str(item.tax_rate),
                    item.position,
                ),
            )
            self._conn.commit()
            return item

    def next_quote_number(self, organisation_id: str) -> str:
        return self._next_number(f"{organisation_id}:quote", "Q-")

    @staticmethod
    def _row_to_quote(row: sqlite3.Row, item_rows: list[sqlite3.Row]) -> Quote:
        return Quote(
            id=row["id"],
            organisation_id=row["organisation_id"],
            account_id=row["account_id"],
            number=row["number"],
            status=QuoteStatus(row["status"]),
            currency=row["currency"],
            issue_date=date.fromisoformat(row["issue_date"]),
            expiry_date=date.fromisoformat(row["expiry_date"]) if row["expiry_date"] else None,
            created_at=datetime.fromisoformat(row["created_at"]),
            line_items=[SqliteRepository._row_to_line_item(r) for r in item_rows],
        )

    # -- Invoices --------------------------------------------------------------

    def create_invoice(self, invoice: Invoice) -> Invoice:
        with self._lock:
            self._conn.execute(
                "INSERT INTO invoices (id, organisation_id, account_id, quote_id, number, status, "
                "currency, issue_date, due_date, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                (
                    invoice.id,
                    invoice.organisation_id,
                    invoice.account_id,
                    invoice.quote_id,
                    invoice.number,
                    invoice.status.value,
                    invoice.currency,
                    invoice.issue_date.isoformat(),
                    invoice.due_date.isoformat() if invoice.due_date else None,
                    invoice.created_at.isoformat(),
                ),
            )
            self._conn.commit()
            return invoice

    def get_invoice(self, organisation_id: str, invoice_id: str) -> Invoice | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM invoices WHERE id = ? AND organisation_id = ?",
                (invoice_id, organisation_id),
            ).fetchone()
            if row is None:
                return None
            item_rows = self._conn.execute(
                "SELECT * FROM invoice_line_items WHERE invoice_id = ? ORDER BY position", (invoice_id,)
            ).fetchall()
        return self._row_to_invoice(row, item_rows)

    def list_invoices(
        self,
        organisation_id: str,
        *,
        account_id: str | None = None,
        account_name: str | None = None,
        status: InvoiceStatus | None = None,
        limit: int | None = None,
        offset: int = 0,
    ) -> tuple[list[Invoice], int]:
        # ORDER BY invoices.rowid, limit=None meaning "every row" - see
        # list_accounts' comment above for both.
        join = ""
        where = "invoices.organisation_id = ?"
        params: list[object] = [organisation_id]
        if account_id is not None:
            where += " AND invoices.account_id = ?"
            params.append(account_id)
        if status is not None:
            where += " AND invoices.status = ?"
            params.append(status.value)
        if account_name:
            # An invoice's account_id always points at exactly one account,
            # so this join can never multiply an invoice's row - no DISTINCT
            # needed.
            join = " JOIN accounts ON accounts.id = invoices.account_id"
            where += " AND accounts.business_name LIKE ?"
            params.append(f"%{account_name}%")

        with self._lock:
            if limit is None:
                rows = self._conn.execute(
                    f"SELECT invoices.* FROM invoices{join} WHERE {where} ORDER BY invoices.rowid", params
                ).fetchall()
                total = len(rows)
            else:
                total = self._conn.execute(
                    f"SELECT COUNT(*) FROM invoices{join} WHERE {where}", params
                ).fetchone()[0]
                rows = self._conn.execute(
                    f"SELECT invoices.* FROM invoices{join} WHERE {where} "
                    "ORDER BY invoices.rowid LIMIT ? OFFSET ?",
                    [*params, limit, offset],
                ).fetchall()
            invoices = []
            for row in rows:
                item_rows = self._conn.execute(
                    "SELECT * FROM invoice_line_items WHERE invoice_id = ? ORDER BY position", (row["id"],)
                ).fetchall()
                invoices.append(self._row_to_invoice(row, item_rows))
        return invoices, total

    def update_invoice(self, invoice: Invoice) -> Invoice:
        with self._lock:
            self._conn.execute(
                "UPDATE invoices SET number = ?, status = ?, currency = ?, issue_date = ?, due_date = ? "
                "WHERE id = ? AND organisation_id = ?",
                (
                    invoice.number,
                    invoice.status.value,
                    invoice.currency,
                    invoice.issue_date.isoformat(),
                    invoice.due_date.isoformat() if invoice.due_date else None,
                    invoice.id,
                    invoice.organisation_id,
                ),
            )
            self._conn.commit()
            return invoice

    def add_invoice_line_item(self, invoice_id: str, item: LineItem) -> LineItem:
        with self._lock:
            self._conn.execute(
                "INSERT INTO invoice_line_items "
                "(id, invoice_id, description, quantity, unit_price, tax_rate, position) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    item.id,
                    invoice_id,
                    item.description,
                    str(item.quantity),
                    str(item.unit_price),
                    str(item.tax_rate),
                    item.position,
                ),
            )
            self._conn.commit()
            return item

    def next_invoice_number(self, organisation_id: str) -> str:
        return self._next_number(f"{organisation_id}:invoice", "INV-")

    @staticmethod
    def _row_to_invoice(row: sqlite3.Row, item_rows: list[sqlite3.Row]) -> Invoice:
        return Invoice(
            id=row["id"],
            organisation_id=row["organisation_id"],
            account_id=row["account_id"],
            quote_id=row["quote_id"],
            number=row["number"],
            status=InvoiceStatus(row["status"]),
            currency=row["currency"],
            issue_date=date.fromisoformat(row["issue_date"]),
            due_date=date.fromisoformat(row["due_date"]) if row["due_date"] else None,
            created_at=datetime.fromisoformat(row["created_at"]),
            line_items=[SqliteRepository._row_to_line_item(r) for r in item_rows],
        )

    @staticmethod
    def _row_to_line_item(row: sqlite3.Row) -> LineItem:
        return LineItem(
            id=row["id"],
            description=row["description"],
            quantity=Decimal(row["quantity"]),
            unit_price=Decimal(row["unit_price"]),
            tax_rate=Decimal(row["tax_rate"]),
            position=row["position"],
        )

    # -- Expenses --------------------------------------------------------------

    def create_expense(self, expense: Expense) -> Expense:
        with self._lock:
            self._conn.execute(
                "INSERT INTO expenses (id, organisation_id, account_id, number, currency, issue_date, "
                "created_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    expense.id,
                    expense.organisation_id,
                    expense.account_id,
                    expense.number,
                    expense.currency,
                    expense.issue_date.isoformat(),
                    expense.created_at.isoformat(),
                ),
            )
            self._conn.commit()
            return expense

    def get_expense(self, organisation_id: str, expense_id: str) -> Expense | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM expenses WHERE id = ? AND organisation_id = ?",
                (expense_id, organisation_id),
            ).fetchone()
            if row is None:
                return None
            item_rows = self._conn.execute(
                "SELECT * FROM expense_line_items WHERE expense_id = ? ORDER BY position", (expense_id,)
            ).fetchall()
            attachment_rows = self._conn.execute(
                "SELECT * FROM expense_attachments WHERE expense_id = ? ORDER BY rowid", (expense_id,)
            ).fetchall()
        return self._row_to_expense(row, item_rows, attachment_rows)

    def list_expenses(self, organisation_id: str, account_id: str | None = None) -> list[Expense]:
        # ORDER BY rowid - see list_accounts' comment above.
        with self._lock:
            if account_id is None:
                rows = self._conn.execute(
                    "SELECT * FROM expenses WHERE organisation_id = ? ORDER BY rowid",
                    (organisation_id,),
                ).fetchall()
            else:
                rows = self._conn.execute(
                    "SELECT * FROM expenses WHERE organisation_id = ? AND account_id = ? ORDER BY rowid",
                    (organisation_id, account_id),
                ).fetchall()
            expenses = []
            for row in rows:
                item_rows = self._conn.execute(
                    "SELECT * FROM expense_line_items WHERE expense_id = ? ORDER BY position", (row["id"],)
                ).fetchall()
                attachment_rows = self._conn.execute(
                    "SELECT * FROM expense_attachments WHERE expense_id = ? ORDER BY rowid", (row["id"],)
                ).fetchall()
                expenses.append(self._row_to_expense(row, item_rows, attachment_rows))
        return expenses

    def add_expense_line_item(self, expense_id: str, item: LineItem) -> LineItem:
        with self._lock:
            self._conn.execute(
                "INSERT INTO expense_line_items "
                "(id, expense_id, description, quantity, unit_price, tax_rate, position) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    item.id,
                    expense_id,
                    item.description,
                    str(item.quantity),
                    str(item.unit_price),
                    str(item.tax_rate),
                    item.position,
                ),
            )
            self._conn.commit()
            return item

    def next_expense_number(self, organisation_id: str) -> str:
        return self._next_number(f"{organisation_id}:expense", "EXP-")

    @staticmethod
    def _row_to_expense(
        row: sqlite3.Row, item_rows: list[sqlite3.Row], attachment_rows: list[sqlite3.Row]
    ) -> Expense:
        return Expense(
            id=row["id"],
            organisation_id=row["organisation_id"],
            account_id=row["account_id"],
            number=row["number"],
            currency=row["currency"],
            issue_date=date.fromisoformat(row["issue_date"]),
            created_at=datetime.fromisoformat(row["created_at"]),
            line_items=[SqliteRepository._row_to_line_item(r) for r in item_rows],
            attachments=[SqliteRepository._row_to_expense_attachment(r) for r in attachment_rows],
        )

    # -- Expense attachments ----------------------------------------------------

    def create_expense_attachment(self, attachment: ExpenseAttachment) -> ExpenseAttachment:
        with self._lock:
            self._conn.execute(
                "INSERT INTO expense_attachments "
                "(id, expense_id, filename, content_type, size, created_at) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    attachment.id,
                    attachment.expense_id,
                    attachment.filename,
                    attachment.content_type,
                    attachment.size,
                    attachment.created_at.isoformat(),
                ),
            )
            self._conn.commit()
            return attachment

    def list_expense_attachments(self, expense_id: str) -> list[ExpenseAttachment]:
        with self._lock:
            rows = self._conn.execute(
                "SELECT * FROM expense_attachments WHERE expense_id = ? ORDER BY rowid", (expense_id,)
            ).fetchall()
        return [self._row_to_expense_attachment(row) for row in rows]

    def get_expense_attachment(self, expense_id: str, attachment_id: str) -> ExpenseAttachment | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM expense_attachments WHERE id = ? AND expense_id = ?",
                (attachment_id, expense_id),
            ).fetchone()
        return self._row_to_expense_attachment(row) if row else None

    def delete_expense_attachment(self, expense_id: str, attachment_id: str) -> None:
        with self._lock:
            self._conn.execute(
                "DELETE FROM expense_attachments WHERE id = ? AND expense_id = ?",
                (attachment_id, expense_id),
            )
            self._conn.commit()

    @staticmethod
    def _row_to_expense_attachment(row: sqlite3.Row) -> ExpenseAttachment:
        return ExpenseAttachment(
            id=row["id"],
            expense_id=row["expense_id"],
            filename=row["filename"],
            content_type=row["content_type"],
            size=row["size"],
            created_at=datetime.fromisoformat(row["created_at"]),
        )

    # -- Registration invites ---------------------------------------------------

    def create_registration_invite(self, invite: RegistrationInvite) -> RegistrationInvite:
        with self._lock:
            self._conn.execute(
                "INSERT INTO registration_invites (token, created_at, expires_at, used_at) "
                "VALUES (?, ?, ?, ?)",
                (
                    invite.token,
                    invite.created_at.isoformat(),
                    invite.expires_at.isoformat(),
                    invite.used_at.isoformat() if invite.used_at else None,
                ),
            )
            self._conn.commit()
            return invite

    def get_registration_invite(self, token: str) -> RegistrationInvite | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM registration_invites WHERE token = ?", (token,)
            ).fetchone()
        return self._row_to_registration_invite(row) if row else None

    def consume_registration_invite(self, token: str, used_at: datetime) -> bool:
        # A single locked UPDATE guarded by `used_at IS NULL`, not a separate
        # check-then-update - two concurrent submissions of the same token
        # must not both succeed (see CLAUDE.md's add_organisation_member
        # race-fix precedent for the same "atomic check-then-claim" shape).
        with self._lock:
            cursor = self._conn.execute(
                "UPDATE registration_invites SET used_at = ? WHERE token = ? AND used_at IS NULL",
                (used_at.isoformat(), token),
            )
            self._conn.commit()
            return cursor.rowcount > 0

    @staticmethod
    def _row_to_registration_invite(row: sqlite3.Row) -> RegistrationInvite:
        return RegistrationInvite(
            token=row["token"],
            created_at=datetime.fromisoformat(row["created_at"]),
            expires_at=datetime.fromisoformat(row["expires_at"]),
            used_at=datetime.fromisoformat(row["used_at"]) if row["used_at"] else None,
        )

    # -- Shared --------------------------------------------------------------

    def _next_number(self, name: str, prefix: str) -> str:
        # `name` is "<organisation_id>:quote"/"<organisation_id>:invoice",
        # not just "quote"/"invoice" - each organisation gets its own
        # independent Q-0001/INV-0001 sequence starting from one, rather
        # than a single global counter that would leak how many
        # quotes/invoices *other* organisations have created (their own
        # numbers jumping straight to Q-0047 on their very first quote).
        # No schema change needed for this - `counters.name` was already a
        # free-text key, not literally constrained to "quote"/"invoice", and
        # organisation_id being a UUID string rather than an int works
        # exactly the same way embedded in this key.
        with self._lock:
            row = self._conn.execute("SELECT value FROM counters WHERE name = ?", (name,)).fetchone()
            value = (row["value"] if row else 0) + 1
            self._conn.execute(
                "INSERT INTO counters (name, value) VALUES (?, ?) "
                "ON CONFLICT(name) DO UPDATE SET value = excluded.value",
                (name, value),
            )
            self._conn.commit()
        return f"{prefix}{value:04d}"
