from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import ROUND_HALF_UP, Decimal
from enum import StrEnum

_CENT = Decimal("0.01")


class QuoteStatus(StrEnum):
    DRAFT = "draft"
    SENT = "sent"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    EXPIRED = "expired"
    CONVERTED = "converted"


class InvoiceStatus(StrEnum):
    DRAFT = "draft"
    SENT = "sent"
    PAID = "paid"
    OVERDUE = "overdue"
    VOID = "void"


@dataclass
class Organisation:
    """The tenant boundary: every Account/Quote/Invoice belongs to exactly
    one Organisation, and a user can only see/touch data in their own (see
    CLAUDE.md). Currently always exactly one member (see
    `organisation_members` in storage/schema.py, UNIQUE on user_id) -
    auto-created the first time a login user needs one
    (OrganisationService.get_or_create_for_user). The UNIQUE constraint is
    deliberately the *only* thing standing in the way of multiple users
    sharing one Organisation later; the shape here doesn't need to change
    for that, just the constraint and an invite/add-member flow.

    `id` is a UUID4 string (see ids.py), generated by the service layer
    before this is constructed - never None, and never an autoincrementing
    integer. See CLAUDE.md for why every id in this app is opaque and
    non-sequential, matching sessionkit's own User.id since v0.2.0."""

    id: str
    name: str
    created_at: datetime


@dataclass
class Account:
    """A business we provide a service to and bill via quotes/invoices.

    Address fields follow the same UK GOV.UK Design System pattern as
    `BusinessProfile` (`address_line1`/`address_line2`/`town_or_city`/
    `county`/`postcode`) rather than one free-text field - see CLAUDE.md and
    data-model.md. Unlike `BusinessProfile`'s fully-optional address,
    `address_line1` here is required (enforced non-blank in
    `AccountService`, never in storage) - an `Account` is a real client
    being billed, not the user's own optionally-published details; the
    remaining lines are each independently optional, same "no all or
    nothing" rule."""

    id: str
    organisation_id: str
    business_name: str
    contact_name: str | None
    email: str
    phone: str | None
    address_line1: str
    address_line2: str | None
    town_or_city: str | None
    county: str | None
    postcode: str | None
    created_at: datetime


@dataclass
class Domain:
    """A domain name owned by an `Account` - which domain, when it expires,
    and who it's registered with. Structurally closest to
    `ExpenseAttachment` below, not `Expense`: always accessed through its
    parent `Account` (no `organisation_id` column of its own - tenant
    ownership is resolved via `AccountService.get_account` first, same
    reasoning as `ExpenseAttachment`'s own docstring), no `number`/
    lifecycle. Unlike `ExpenseAttachment` though, it's user-edited data,
    not an immutable uploaded file, so it supports a full update
    (`DomainService.update_domain`, mirroring
    `AccountService.update_account`'s full-replace semantics) rather than
    being add-only.

    `domain_name`/`registrar` are both required (enforced non-blank in
    `DomainService`, never in storage, same "required but unvalidated
    format" convention as `Account.business_name`/`email` - this app
    doesn't validate email format either, so there's no reason to expect a
    domain-name-shaped regex check here). `expiry_date` is also required -
    a domain with no known expiry isn't a useful record. `auto_renew`
    defaults `False` and is purely informational, same as everything in
    `BusinessProfile`'s payment-and-tax group - nothing here talks to a
    registrar's API."""

    id: str
    account_id: str
    domain_name: str
    expiry_date: date
    registrar: str
    auto_renew: bool
    created_at: datetime
    updated_at: datetime


@dataclass
class BusinessProfile:
    """The logged-in user's own business details - not a domain "Account"
    (that's the client being billed) and not sessionkit's User (that's the
    login identity). One per user, keyed by sessionkit's user id - see
    CLAUDE.md for why that's a plain column, not an enforced foreign key.

    title/first_name/last_name are the account holder's own name (title is
    the only optional one of the three, e.g. "Mr"/"Dr" - a form nicety, not
    something anyone should be blocked from saving without). business_name
    is still required; the address fields are not (a sole trader may
    legally trade under their home address and not want it on every
    document, or simply not have filled it in yet) - each line is
    independently optional, not "all or nothing", to avoid inventing a
    cross-field validation rule nobody asked for.

    Address fields follow the UK GOV.UK Design System's standard address
    pattern (address_line1/2, town_or_city, county, postcode) rather than a
    single free-text field - see CLAUDE.md and data-model.md.

    currency is this user's *reporting* currency - the one the home
    dashboard's monthly totals are summed in (see
    InvoiceService.monthly_totals). It's independent of the currency chosen
    per quote/invoice (Quote.currency/Invoice.currency default to "USD" but
    are freely chosen at creation) - an invoice in a different currency than
    this setting is simply excluded from that report rather than
    naively summed into it. Defaults to "GBP".

    bank_account_name/bank_sort_code/bank_account_number sit in the same
    "payment and tax settings" group as payment_terms_days/utr/vat_number -
    each independently optional, and (like every other field here) purely
    informational: nothing in this codebase validates a sort code's format
    or checks a bank account actually exists. Rendered as a "Payment
    details" section on generated invoices only, never quotes or expenses
    (see pdf.py's bank_details_lines/render_invoice_pdf) - there's nothing
    to pay yet against a quote, and an expense is money already spent, not
    billed to the account.

    quote_document_header/quote_document_footer,
    invoice_document_header/invoice_document_footer, and
    expense_document_header/expense_document_footer are three independent
    pairs of free text (blank lines allowed, trimmed and dropped when
    rendering - see pdf.py's quote_header_lines/quote_footer_lines and its
    invoice_/expense_ equivalents), one pair per document type so each can
    say something different - inserted into every quote/invoice/expense PDF
    this user generates respectively: the header before the title, the
    footer after the totals table. Deliberately simple - not per-page
    running headers/footers (that would need CSS position: running()/
    @page margin-box content, a bigger lift than anything asked for), just fixed
    text once at the top and bottom of the document, which is enough for
    the common case (a slogan/company registration number up top, payment
    terms or a thank-you note at the bottom) on the short, mostly-single-
    page documents this app generates.

    accent_color is a single `#RRGGBB` hex string (e.g. "#2563EB") used as
    the brand colour across every quote/invoice/expense PDF this user
    generates (the title, the line-items table header, the totals
    highlight - see pdf.py) - one shared value, not a per-document-type
    triple like the header/footer pairs above, since it's "this business's
    colour" rather than something that varies by document type. Nullable -
    pdf.py falls back to a fixed neutral constant when unset, so a PDF
    still looks finished before anyone visits Settings. Unlike every other
    field on this class, its format *is* validated
    (BusinessProfileService.save_profile) rather than accepted as free-form
    text: it's interpolated directly into a CSS declaration in the
    rendered template, not shown as escaped body text, so a malformed
    value is a real injection boundary, not just a cosmetic format
    check."""

    id: str
    user_id: str
    title: str | None
    first_name: str
    last_name: str
    business_name: str
    address_line1: str | None
    address_line2: str | None
    town_or_city: str | None
    county: str | None
    postcode: str | None
    payment_terms_days: int
    currency: str
    utr: str | None
    vat_number: str | None
    bank_account_name: str | None
    bank_sort_code: str | None
    bank_account_number: str | None
    quote_document_header: str | None
    quote_document_footer: str | None
    invoice_document_header: str | None
    invoice_document_footer: str | None
    expense_document_header: str | None
    expense_document_footer: str | None
    accent_color: str | None
    created_at: datetime
    updated_at: datetime


@dataclass
class LineItem:
    """tax_rate is a fraction (`Decimal("0.20")` for 20% VAT, `Decimal("0")`
    for none) applied to this line only - there's no invoice-wide rate,
    since different lines can legitimately carry different UK VAT rates
    (standard 20%/reduced 5%/zero 0%). `total` is *gross* (`net_total +
    tax_amount`) - the amount this line actually adds to what's owed; use
    `net_total`/`tax_amount` for the pre-tax amount and the tax alone."""

    id: str
    description: str
    quantity: Decimal
    unit_price: Decimal
    tax_rate: Decimal
    position: int

    @property
    def net_total(self) -> Decimal:
        return self.quantity * self.unit_price

    @property
    def tax_amount(self) -> Decimal:
        # Rounded to the minor currency unit (cents/pence) - net_total * a
        # 2dp tax_rate otherwise carries extra decimal places (e.g.
        # 100.00 * 0.20 = 20.0000) that don't correspond to real money.
        return (self.net_total * self.tax_rate).quantize(_CENT, rounding=ROUND_HALF_UP)

    @property
    def total(self) -> Decimal:
        return self.net_total + self.tax_amount


@dataclass
class Quote:
    id: str
    organisation_id: str
    account_id: str
    number: str | None
    status: QuoteStatus
    currency: str
    issue_date: date
    expiry_date: date | None
    created_at: datetime
    line_items: list[LineItem] = field(default_factory=list)

    @property
    def subtotal(self) -> Decimal:
        return sum((item.net_total for item in self.line_items), Decimal("0"))

    @property
    def tax_total(self) -> Decimal:
        return sum((item.tax_amount for item in self.line_items), Decimal("0"))

    @property
    def total(self) -> Decimal:
        return sum((item.total for item in self.line_items), Decimal("0"))


@dataclass
class Invoice:
    id: str
    organisation_id: str
    account_id: str
    quote_id: str | None
    number: str | None
    status: InvoiceStatus
    currency: str
    issue_date: date
    due_date: date | None
    created_at: datetime
    line_items: list[LineItem] = field(default_factory=list)

    @property
    def subtotal(self) -> Decimal:
        return sum((item.net_total for item in self.line_items), Decimal("0"))

    @property
    def tax_total(self) -> Decimal:
        return sum((item.tax_amount for item in self.line_items), Decimal("0"))

    @property
    def total(self) -> Decimal:
        return sum((item.total for item in self.line_items), Decimal("0"))


@dataclass
class ExpenseAttachment:
    """A supplementary file (e.g. a scanned receipt) uploaded against an
    Expense - always a PDF (validated in ExpenseService.add_attachment,
    not here or in storage). This dataclass is metadata only; the bytes
    themselves live on disk, not in SQLite (see attachments.py's
    AttachmentStore) - keyed by `id`, which is also the on-disk filename's
    stem, so nothing here needs to sanitise the caller-supplied
    `filename` for filesystem safety (that string is display-only,
    never used as a path)."""

    id: str
    expense_id: str
    filename: str
    content_type: str
    size: int
    created_at: datetime


@dataclass
class Expense:
    """A cost incurred against an Account - e.g. a domain renewal paid on a
    client's behalf. Unlike Quote/Invoice there's no draft/sent lifecycle
    (see CLAUDE.md): it's a record of money already spent, not a document
    issued to anyone, so there's nothing to "send" - `number` (EXP-0001,
    same per-organisation counter pattern as Quote.number/Invoice.number,
    see SqliteRepository.next_expense_number) is assigned immediately at
    creation, and line items can be added any time after, not gated behind
    a status check the way Quote.add_line_item is gated on `draft`. Line
    items share the same shape as Quote/Invoice's (LineItem, including a
    per-line tax_rate) rather than a simpler description+amount shape,
    since VAT paid on a business expense may be separately reclaimable.
    `attachments` (see ExpenseAttachment above) are supplementary PDFs
    (receipts, etc.) uploaded against this expense - also addable at any
    time, same no-lifecycle reasoning as line items."""

    id: str
    organisation_id: str
    account_id: str
    number: str
    currency: str
    issue_date: date
    created_at: datetime
    line_items: list[LineItem] = field(default_factory=list)
    attachments: list[ExpenseAttachment] = field(default_factory=list)

    @property
    def subtotal(self) -> Decimal:
        return sum((item.net_total for item in self.line_items), Decimal("0"))

    @property
    def tax_total(self) -> Decimal:
        return sum((item.tax_amount for item in self.line_items), Decimal("0"))

    @property
    def total(self) -> Decimal:
        return sum((item.total for item in self.line_items), Decimal("0"))


@dataclass
class MonthlyInvoiceTotals:
    """One month's worth of invoice totals, split by paid vs not - see
    InvoiceService.monthly_totals. `month` is "YYYY-MM"."""

    month: str
    paid_total: Decimal
    unpaid_total: Decimal


@dataclass
class MonthlyExpenseTotals:
    """One month's worth of expense totals - see
    ExpenseService.monthly_totals. `month` is "YYYY-MM", same format as
    MonthlyInvoiceTotals. No paid/unpaid split, unlike invoices - an
    Expense has no status to split on (see models.Expense)."""

    month: str
    total: Decimal


@dataclass
class Stats:
    """All-time, organisation-scoped counters for the home dashboard's
    stats section - see StatsService.get_stats. Deliberately a small, flat
    dataclass rather than one field per entity type growing organically -
    add fields here as new stats are actually asked for, not speculatively.
    `quotes_sent_count`/`quotes_converted_count` are two raw counts rather
    than a precomputed rate - dividing them (and handling the "no quotes
    sent yet" case) is left to the caller, same as `isOverdue`/
    `isOutstanding` being computed client-side on HomePage.tsx rather than
    baked into the API response. `total_paid` follows
    InvoiceService.monthly_totals' currency-filtering convention: only
    invoices in the currency the caller asked for count, others are
    excluded rather than naively summed in - see StatsService.get_stats."""

    account_count: int
    quote_count: int
    invoice_count: int
    quotes_sent_count: int
    quotes_converted_count: int
    total_paid: Decimal


@dataclass
class Page[T]:
    """One page of a `list_*` service method's results, alongside `total` -
    the number of rows matching the same filters across *every* page, not
    just this one - see AccountService.list_accounts/QuoteService.
    list_quotes/InvoiceService.list_invoices. `total` lets a caller compute
    how many pages exist without a second round trip. One small generic
    wrapper reused by all three rather than three near-identical bespoke
    classes."""

    items: list[T]
    total: int


@dataclass
class RegistrationInvite:
    """A single-use, time-limited token gating the public `/register` page
    (see `api/auth.py`'s `POST /auth/register`, `cli/main.py`'s `invite
    create`) - the only way to create a new sessionkit login without the
    `sessionkit` CLI directly (see CLAUDE.md's "no public signup" note,
    now qualified by this invite-gated exception).

    `token` is a UUID4 (see ids.py), generated by
    `RegistrationInviteService.create_invite` before this is constructed -
    same convention as every other id in this app - and doubles as the
    primary key, since nothing else ever needs to look one of these up.
    Not tied to a specific email nor to an `Organisation`: whoever holds a
    valid token can register with any email, and their own `Organisation`
    is created lazily on first login, exactly like every other user
    (`OrganisationService.get_or_create_for_user`) - registration itself
    doesn't touch organisations at all.

    `used_at` is `None` until consumed; `RegistrationInviteService.
    check_invite` treats an unknown token, an expired one
    (`expires_at` in the past), and an already-used one identically -
    raising the same `NotFound` for all three, deliberately, so a caller
    (or an attacker probing tokens) can't distinguish "never existed" from
    "used already" from "expired" from the response alone."""

    token: str
    created_at: datetime
    expires_at: datetime
    used_at: datetime | None
