from typing import Protocol

from .models import Account, BusinessProfile, Invoice, LineItem, Organisation, Quote


class Repository(Protocol):
    def close(self) -> None: ...

    def get_organisation_id_for_user(self, user_id: int) -> int | None: ...
    def create_organisation(self, organisation: Organisation) -> Organisation: ...
    def add_organisation_member(self, organisation_id: int, user_id: int) -> int: ...

    def create_account(self, account: Account) -> Account: ...
    def get_account(self, organisation_id: int, account_id: int) -> Account | None: ...
    def list_accounts(self, organisation_id: int) -> list[Account]: ...
    def update_account(self, account: Account) -> Account: ...

    def get_business_profile(self, user_id: int) -> BusinessProfile | None: ...
    def upsert_business_profile(self, profile: BusinessProfile) -> BusinessProfile: ...

    def create_quote(self, quote: Quote) -> Quote: ...
    def get_quote(self, organisation_id: int, quote_id: int) -> Quote | None: ...
    def list_quotes(self, organisation_id: int, account_id: int | None = None) -> list[Quote]: ...
    def update_quote(self, quote: Quote) -> Quote: ...
    def add_quote_line_item(self, quote_id: int, item: LineItem) -> LineItem: ...
    def next_quote_number(self, organisation_id: int) -> str: ...

    def create_invoice(self, invoice: Invoice) -> Invoice: ...
    def get_invoice(self, organisation_id: int, invoice_id: int) -> Invoice | None: ...
    def list_invoices(self, organisation_id: int, account_id: int | None = None) -> list[Invoice]: ...
    def update_invoice(self, invoice: Invoice) -> Invoice: ...
    def add_invoice_line_item(self, invoice_id: int, item: LineItem) -> LineItem: ...
    def next_invoice_number(self, organisation_id: int) -> str: ...
