from datetime import datetime
from typing import Protocol

from .models import (
    Account,
    BusinessProfile,
    Domain,
    Expense,
    ExpenseAttachment,
    Invoice,
    InvoiceStatus,
    LineItem,
    Organisation,
    Quote,
    QuoteStatus,
    Registrar,
    RegistrationInvite,
)


class Repository(Protocol):
    def close(self) -> None: ...

    def get_organisation_id_for_user(self, user_id: str) -> str | None: ...
    def create_organisation(self, organisation: Organisation) -> Organisation: ...
    def add_organisation_member(self, organisation_id: str, user_id: str) -> str: ...

    def create_account(self, account: Account) -> Account: ...
    def get_account(self, organisation_id: str, account_id: str) -> Account | None: ...
    def list_accounts(
        self, organisation_id: str, *, query: str | None = None, limit: int | None = None, offset: int = 0
    ) -> tuple[list[Account], int]: ...
    def update_account(self, account: Account) -> Account: ...

    def get_business_profile(self, user_id: str) -> BusinessProfile | None: ...
    def upsert_business_profile(self, profile: BusinessProfile) -> BusinessProfile: ...

    def create_quote(self, quote: Quote) -> Quote: ...
    def get_quote(self, organisation_id: str, quote_id: str) -> Quote | None: ...
    def list_quotes(
        self,
        organisation_id: str,
        *,
        account_id: str | None = None,
        account_name: str | None = None,
        status: QuoteStatus | None = None,
        limit: int | None = None,
        offset: int = 0,
    ) -> tuple[list[Quote], int]: ...
    def update_quote(self, quote: Quote) -> Quote: ...
    def add_quote_line_item(self, quote_id: str, item: LineItem) -> LineItem: ...
    def next_quote_number(self, organisation_id: str) -> str: ...

    def create_invoice(self, invoice: Invoice) -> Invoice: ...
    def get_invoice(self, organisation_id: str, invoice_id: str) -> Invoice | None: ...
    def list_invoices(
        self,
        organisation_id: str,
        *,
        account_id: str | None = None,
        account_name: str | None = None,
        status: InvoiceStatus | None = None,
        quote_id: str | None = None,
        limit: int | None = None,
        offset: int = 0,
    ) -> tuple[list[Invoice], int]: ...
    def update_invoice(self, invoice: Invoice) -> Invoice: ...
    def add_invoice_line_item(self, invoice_id: str, item: LineItem) -> LineItem: ...
    def next_invoice_number(self, organisation_id: str) -> str: ...

    def create_expense(self, expense: Expense) -> Expense: ...
    def get_expense(self, organisation_id: str, expense_id: str) -> Expense | None: ...
    def list_expenses(self, organisation_id: str, account_id: str | None = None) -> list[Expense]: ...
    def add_expense_line_item(self, expense_id: str, item: LineItem) -> LineItem: ...
    def next_expense_number(self, organisation_id: str) -> str: ...
    def update_expense_date(self, expense: Expense) -> Expense: ...

    def create_domain(self, domain: Domain) -> Domain: ...
    def get_domain(self, account_id: str, domain_id: str) -> Domain | None: ...
    def list_domains(self, account_id: str) -> list[Domain]: ...
    def update_domain(self, domain: Domain) -> Domain: ...
    def delete_domain(self, account_id: str, domain_id: str) -> None: ...

    def create_expense_attachment(self, attachment: ExpenseAttachment) -> ExpenseAttachment: ...
    def list_expense_attachments(self, expense_id: str) -> list[ExpenseAttachment]: ...
    def get_expense_attachment(self, expense_id: str, attachment_id: str) -> ExpenseAttachment | None: ...
    def delete_expense_attachment(self, expense_id: str, attachment_id: str) -> None: ...

    def create_registrar(self, registrar: Registrar) -> Registrar: ...
    def get_registrar(self, organisation_id: str, registrar_id: str) -> Registrar | None: ...
    def list_registrars(self, organisation_id: str) -> list[Registrar]: ...
    def update_registrar(self, registrar: Registrar) -> Registrar: ...
    def delete_registrar(self, organisation_id: str, registrar_id: str) -> None: ...

    def create_registration_invite(self, invite: RegistrationInvite) -> RegistrationInvite: ...
    def get_registration_invite(self, token: str) -> RegistrationInvite | None: ...
    def consume_registration_invite(self, token: str, used_at: datetime) -> bool: ...
